### ISSUE TITLE
GW-005 Game Prototype

### ISSUE THREAD

**Issue by IrenaRuprecht** [sw21-tug/Team_24#5]
**As a** User
**I want** to see an interface that keeps showing me words for 90 seconds as long I press the correct button or skip the word by pressing the skip button. 
**so that** I can perform as many words as I can in 90 seconds.

Acceptance Criteria:

- [x] Simple Interface that displays a word, a timer, an option to mark the word as guessed correctly.
- [x] Show new words as long as the timer has not run out.
- [x] Show new word if the skip button or the correct button is pressed.

**Comment by agape94** [comment]
* If we run out of words in the pool -> keep showing words for now
* For now go directly from startup page to game
