### ISSUE TITLE
GW-007 P2P Connection

### ISSUE THREAD

**Issue by IrenaRuprecht** [sw21-tug/Team_24#7]
**As a** User
**I want** to host a local game or find other local games to join 
**so that** play together with my friends.

Acceptance Criteria:

- [x] Simple interface for hosting, searching and joining guessing word games. 
- [x] Local Peer-to-Peer connection between at least two Android devices.
- [x] Simple interface that displays connected users.

**Comment by icezyclon** [comment]
Some resources:

Regarding game discovery: NSD looks promising.
https://developer.android.com/training/connect-devices-wirelessly/nsd#kotlin

There is also NSD using Wifi-Direct instead:
https://developer.android.com/training/connect-devices-wirelessly/nsd-wifi-direct

Using Wifi-Direct for Peer-to-Peer connection:
https://developer.android.com/guide/topics/connectivity/wifip2p
